### ISSUE TITLE
Peer to peer code review - 4 Jan

### ISSUE THREAD

**Issue by andres-condezo** [gabyse1/repo-awesome-books#2]
## HI @gabyse1 and @MrRamoun 
Good job so far!

## Highlights
- Clean code 🟢 
- Great variable names🟢 
![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 

Cheers and Happy coding!

**Comment by fherrerao** [comment]
# Good job team

- Your project looks great.
- The functionality works perfectly.

**Comment by gabyse1** [comment]
Thank you for your comments.
